In [1]:
import numpy as np

Mini Project

In [2]:
#1. **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
# students=np.array(["A","B","C"])
# subjects=np.array(["Math","Eng","Sci"])
marks=np.array([[80,60,70],
               [65,75,85],
                [87,68,88]])
# print(students)
# print(subjects)
print(marks)


[[80 60 70]
 [65 75 85]
 [87 68 88]]


In [3]:
#2. **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
print("The size of the array is",marks.size)
print("The dimension of the array is",marks.ndim)

The size of the array is 9
The dimension of the array is 2


In [4]:
#3.**Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
print(marks.reshape(-1)) #This converts the array into 1D array
marks.reshape(3,3) #This is used to transform the 1D array back into 2D format

[80 60 70 65 75 85 87 68 88]


array([[80, 60, 70],
       [65, 75, 85],
       [87, 68, 88]])

In [5]:
#4.**Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
#Here a new data is added into the array and arranged using vertical stack
new_st=np.array([85,74,79])
marks=np.vstack((marks,new_st))
marks

array([[80, 60, 70],
       [65, 75, 85],
       [87, 68, 88],
       [85, 74, 79]])

In [6]:
#5. **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
# Data present in the array is modified and the value is changed
marks[1,1]=90
marks


array([[80, 60, 70],
       [65, 90, 85],
       [87, 68, 88],
       [85, 74, 79]])

In [7]:
#6.**Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
marks_float = marks.astype(float)
marks_float
marks.dtype

dtype('int64')

In [8]:
#7. **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.
marks1=marks
view1=marks1.view()
view1[0,0]=100
view1

copy1=marks.copy()
copy1[0,0]=100
copy1

array([[100,  60,  70],
       [ 65,  90,  85],
       [ 87,  68,  88],
       [ 85,  74,  79]])